version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: qrlMYSQL22!!
    networks:
      - my-network
    ports:
      - "3306:3306"  # Expose app service on port 8080
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d

  app:
    image: backend-api
    networks:
      - my-network
    depends_on:
      - db
    ports:
      - "8080:8080"  # Expose app service on port 8080

  ui:
    image: frontend-app
    networks:
      - my-network
    depends_on:
      - app
    ports:
      - "5173:5173"  # Expose UI service on port 3000
    environment:
      - VITE_PORT=5173

networks:
  my-network:
    driver: bridge
